In [1]:
import math

num = 25.8

print("Number =", num)
print("Floor =", math.floor(num))
print("Ceil =", math.ceil(num))
print("Square Root of 64 =", math.sqrt(64))
print("Integer Square Root of 25 =", math.isqrt(25))
print("GCD of 24 and 36 =", math.gcd(24, 36))

Number = 25.8
Floor = 25
Ceil = 26
Square Root of 64 = 8.0
Integer Square Root of 25 = 5
GCD of 24 and 36 = 12


In [2]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print("Array:")
print(arr)

print("Number of Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)

print("Sum:", arr.sum())
print("Mean:", arr.mean())

print("Sorted Array:")
print(np.sort(arr))

print("Sine Values:")
print(np.sin(arr))

Array:
[[10 20 30]
 [40 50 60]]
Number of Dimensions: 2
Shape: (2, 3)
Size: 6
Sum: 210
Mean: 35.0
Sorted Array:
[[10 20 30]
 [40 50 60]]
Sine Values:
[[-0.54402111  0.91294525 -0.98803162]
 [ 0.74511316 -0.26237485 -0.30481062]]


In [3]:
import numpy as np
from scipy import linalg

A = np.array([[2, 3],
              [1, 4]])

print("Matrix:")
print(A)

print("Determinant =", linalg.det(A))

eigen_values, eigen_vectors = linalg.eig(A)

print("Eigen Values:")
print(eigen_values)

print("Eigen Vectors:")
print(eigen_vectors)


Matrix:
[[2 3]
 [1 4]]
Determinant = 5.0
Eigen Values:
[1.+0.j 5.+0.j]
Eigen Vectors:
[[-0.9486833  -0.70710678]
 [ 0.31622777 -0.70710678]]
